"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Header from "@/components/Header";
import SignalCard from "@/components/SignalCard";
import { runScanner } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import type { ScannerResult } from "@/lib/types";

export default function SignalsPage() {
  const [signals, setSignals] = useState<ScannerResult[]>([]);
  const [loading, setLoading] = useState(true);
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!authLoading && !user) {
      router.replace("/login");
    }
  }, [user, authLoading, router]);

  useEffect(() => {
    if (authLoading || !user) return;
    async function load() {
      try {
        const data = await runScanner();
        // Backend `top_signals` now carries only the Top 3 (combined pool).
        // The journal keeps ALL eligible signals of the current scan so every
        // quality-approved setup is surfaced, ranked deterministically.
        const top = (data.results || [])
          .filter((r) => r.top_signal_eligible === true)
          .sort((a: ScannerResult, b: ScannerResult) => {
            const ra = a.top_signal_rank ?? Number.MAX_SAFE_INTEGER;
            const rb = b.top_signal_rank ?? Number.MAX_SAFE_INTEGER;
            if (ra !== rb) return ra - rb;
            return (b.confidence || 0) - (a.confidence || 0);
          });
        setSignals(top);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [authLoading, user]);

  return (
    <div className="min-h-screen bg-[#0a0e17]">
      <Header />
      <main className="max-w-[1440px] mx-auto px-4 py-6">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-white">Signal Journal</h1>
          <p className="text-sm text-gray-500">All active signals with multi-factor analysis and confidence scores</p>
          <div className="mt-2 px-3 py-2 bg-blue-500/10 border border-blue-500/30 rounded-lg text-xs text-blue-400">
            Signals are generated by a multi-factor scoring model using yfinance data. Past performance does not guarantee future results. Signal scores are not accuracy guarantees.
          </div>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <div className="w-10 h-10 border-4 border-blue-500/30 border-t-blue-500 rounded-full animate-spin" />
          </div>
        ) : signals.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {signals.map((signal) => (
              <SignalCard
                key={signal.symbol}
                signal={signal.signal_data}
                setupQuality={signal.setup_quality}
                qualityScore={signal.setup_quality_score}
                confirmationCount={signal.confirmation_count}
                confirmationTotal={signal.confirmation_total}
                riskRewardRatio={signal.risk_reward_ratio}
                onClick={() => window.location.href = `/stock/${signal.symbol}`}
              />
            ))}
          </div>
        ) : (
          <div className="card text-center py-16">
            <p className="text-gray-400 text-lg mb-2">No Active Signals</p>
            <p className="text-gray-500 text-sm">
              The signal engine requires multiple independent confirmations to generate a trade setup.
              A high-quality NO TRADE decision is preferable to a low-quality trade.
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
